# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

stages:
- stage: ContinuousIntegration
  displayName: Local Build and Tests
  jobs:
  - job: BuildAndRunTests
    displayName: Build solution and run tests
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '10.x'
    - script: npm install
      displayName: 'Install packages'
      workingDirectory: 'src'
    - script: npm install -g expo-cli
      displayName: 'Install expo'
