variables:
  outputDirectory: $(Build.ArtifactStagingDirectory)
  srcDirectory: "./src"

trigger:
  - main

stages:
  - stage: ContinuousIntegration
    displayName: Local Build and Tests
    jobs:
      - job: BuildAndRunTests
        displayName: Build solution and run tests
        steps:
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: "16.x"

          - script: npm install
            displayName: "Install packages"
            workingDirectory: $(srcDirectory)

          - script: npm run test
            displayName: "Run unit tests"
            workingDirectory: $(srcDirectory)

          - task: PublishTestResults@2
            displayName: "Publish Unit Test Results"
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "test-results/junit.xml"
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: "App Test"

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: "Cobertura"
              summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
              pathToSource: "$(System.DefaultWorkingDirectory)/src"
              failIfCoverageEmpty: true

          - script: npx expo export:web
            displayName: "Generating web version"
            workingDirectory: $(srcDirectory)

          - task: PublishBuildArtifacts@1
            displayName: "Publish artifact"
            inputs:
              PathtoPublish: $(srcDirectory)/web-build
              ArtifactName: "drop"
              publishLocation: "Container"
