export const LAPTIME_MINUTES_UPDATE = "LAPTIME_MINUTES_UPDATE";
export const LAPTIME_SECONDS_UPDATE = "LAPTIME_SECONDS_UPDATE";
export const STINT_CONSUMPTION_UPDATE = "LAPTIME_CONSUMPTION_UPDATE";
export const LAPTIME_FUELTANK_CAPACITY = "LAPTIME_FUELTANK_CAPACITY";
export const LAPTIME_WOULDBE_STINT_DURATION = "LAPTIME_WOULDBE_STINT_DURATION";
