export const LAPTIME_MINUTES_UPDATE = "LAPTIME_MINUTES_UPDATE";
export const LAPTIME_SECONDS_UPDATE = "LAPTIME_SECONDS_UPDATE";
export const LAPTIME_CONSUMPTION_UPDATE = "LAPTIME_CONSUMPTION_UPDATE";
export const LAPTIME_FUELTANK_CONTENT_UPDATE =
  "LAPTIME_FUELTANK_CONTENT_UPDATE";
export const LAPTIME_WOULDBE_STINT_DURATION = "LAPTIME_WOULDBE_STINT_DURATION";
