export const LAPTIME_MINUTES_UPDATE = "LAPTIME_MINUTES_UPDATE";
export const LAPTIME_SECONDS_UPDATE = "LAPTIME_SECONDS_UPDATE";
export const STINT_CONSUMPTION_UPDATE = "STINT_CONSUMPTION_UPDATE";
export const FUELTANK_LITER_UPDATE = "FUELTANK_LITER_UPDATE";
export const WOULDBE_STINT_DURATION_UPDATE = "WOULDBE_STINT_DURATION_UPDATE";
